-- ─── Migration 001: Create Users Table ──────────────────────────────────────
--
-- WHY run migrations instead of just executing SQL manually?
--   Migrations are version-controlled, repeatable, and trackable.
--   Every developer runs the same migrations to get an identical DB state.
--   In production, you can see EXACTLY what changed and when.
--
-- Run this with: psql $DATABASE_URL -f migrations/001_create_users.sql
-- ─────────────────────────────────────────────────────────────────────────────

-- gen_random_uuid() requires the pgcrypto extension.
-- WHY UUID for user ID instead of BIGSERIAL?
--   UUIDs don't reveal how many users you have (INT 1,2,3... does).
--   They're safe to expose in URLs and API responses.
--   They can be generated client-side without a DB round-trip if needed.

CREATE EXTENSION IF NOT EXISTS "pgcrypto";

CREATE TABLE IF NOT EXISTS users (
    -- UUID primary key, auto-generated by Postgres
    id            UUID PRIMARY KEY DEFAULT gen_random_uuid(),

    -- UNIQUE NOT NULL: two users can't have the same email
    -- VARCHAR(255): standard max email length
    email         VARCHAR(255) UNIQUE NOT NULL,

    -- NEVER store plaintext passwords. Store bcrypt hash only.
    -- bcrypt output is always 60 chars, but 255 gives us room if algorithm changes.
    password_hash VARCHAR(255) NOT NULL,

    -- Optional API key for programmatic access (power users)
    -- UNIQUE: each key identifies exactly one user
    api_key       VARCHAR(64) UNIQUE,

    -- CHECK constraint: only allow known plan values — enforced at DB level
    plan          VARCHAR(20) DEFAULT 'free' CHECK (plan IN ('free', 'pro', 'enterprise')),

    -- DEFAULT NOW(): Postgres fills this in automatically on INSERT
    created_at    TIMESTAMP WITH TIME ZONE DEFAULT NOW(),

    -- Nullable: NULL means they've never logged in, or we don't track it yet
    last_login_at TIMESTAMP WITH TIME ZONE
);

-- Index on email: used for login lookup
-- WHY? Every login does SELECT WHERE email = ?
-- Without index: full table scan (O(n)). With index: O(log n).
CREATE UNIQUE INDEX IF NOT EXISTS idx_users_email   ON users(email);

-- Index on api_key: used for API key auth on every protected request
CREATE UNIQUE INDEX IF NOT EXISTS idx_users_api_key ON users(api_key) WHERE api_key IS NOT NULL;
